### PR TITLE
fix: prevent subscription teardown crashes and fix flaky tests

### LINKED ISSUE #296: [BUG] Flaky integration test test_scenario_config_management on Rolling CI
# Bug report

### Steps to reproduce

1. Push any change to a branch with CI enabled
2. Wait for the `build-and-test (rolling, ubuntu:noble)` job
3. Observe `test_scenario_config_management` failing intermittently

### Expected behavior

`test_scenario_config_management` should pass - it launches a single demo node (`temp_sensor`) and waits for the gateway to discover it.

### Actual behavior

The test times out after 60 seconds with:

```
AssertionError: Discovery incomplete after 60.0s - found 2 apps, need 1.
Missing apps: {'temp_sensor'}, Missing areas: set()
```

Key observation: the gateway discovers **2 apps** but none of them is `temp_sensor`. This suggests DDS cross-contamination from other tests leaking through `ROS_DOMAIN_ID` isolation on Rolling.

### Root cause analysis

Three contributing factors:

1. **DDS discovery is slower on Rolling** - newer Fast-RTPS/CycloneDDS version with different timing characteristics. 60-second `DISCOVERY_TIMEOUT` is borderline.

2. **ROS_DOMAIN_ID contamination** - the test found 2 apps instead of the expected 1, but not the right one. This points to stale DDS participants from a previous test bleeding into this test's domain. The CMakeLists.txt already documents this risk:
   ```
   # Each test also gets a unique ROS_DOMAIN_ID to prevent DDS cross-contamination
   # between tests (e.g., stale DDS participants from previous tests leaking into
   # subsequent test's graph discovery).
   ```

3. **CI runner contention** - Docker-based Rolling CI shares resources, adding latency to DDS discovery.

### Proposed fixes (ascending complexity)

**1. Increase `DISCOVERY_TIMEOUT` from 60s to 90s** (1-line change, lowest risk)
- File: `src/ros2_medkit_integration_tests/ros2_medkit_test_utils/constants.py:39`
- CMake scenario test timeout is already 300s, so 90s is well within bounds

**2. Increase ROS_DOMAIN_ID stride for integration tests**
- File: `src/ros2_medkit_integration_tests/CMakeLists.txt`
- Currently domain IDs are sequential (100, 101, 102...). Increasing stride to 2-5 would reduce DDS participant leakage between tests

**3. Increase gateway refresh interval in tests from 1s to 2s**
- File: `src/ros2_medkit_integration_tests/ros2_medkit_test_utils/launch_helpers.py:98`
- Reduces DDS middleware strain, gives more time per cycle

### Environment
- ros2_medkit version: 0.3.0 (main branch, commit bdf6fe3)
- ROS 2 distro: Rolling (ubuntu:noble)
- OS: Ubuntu Noble (24.04) in Docker (GitHub Actions CI)

### Additional information

- CI run: https://github.com/selfpatch/ros2_medkit/actions/runs/23308288985/job/67788427165
- Rolling is already marked `continue-on-error: true` in CI, so this doesn't block PRs
- Jazzy and Humble are not affected - their DDS versions have faster/more reliable discovery
- The same test passes consistently on Jazzy and Humble

### LINKED ISSUE #297: [BUG] Flaky ParamBeaconPluginTest.BackoffOnTimeout on Pixi Humble CI
# Bug report

### Steps to reproduce
1. Merge any PR to main (or push to main)
2. Pixi (humble) CI job runs `test_param_beacon_plugin`
3. `ParamBeaconPluginTest.BackoffOnTimeout` fails intermittently

First observed after merge of PR #289, but unrelated to that PR - the test existed before and the param_beacon package was not modified.

CI run: https://github.com/selfpatch/ros2_medkit/actions/runs/23347979924/job/67918496379

### Expected behavior

Test passes consistently across all CI runners.

### Actual behavior

```
test_param_beacon_plugin.cpp:327: Failure
Value of: stored.has_value()
  Actual: false
  Expected: true
[  FAILED  ] ParamBeaconPluginTest.BackoffOnTimeout (506 ms)
```

### Analysis

The test (`test_param_beacon_plugin.cpp:295-328`) configures:
- Poll interval: 50ms (`setup_plugin(0.05)`)
- 2 consecutive timeouts (`wait_for_service` returns `false` twice) triggering exponential backoff (skip 1 cycle, then skip 2 cycles)
- Fixed `sleep_for(500ms)` waiting for recovery

The backoff sequence is: timeout -> skip 1 cycle -> timeout -> skip 2 cycles -> success. With 50ms intervals, this needs at minimum `(1 + 1 + 1 + 2 + 1) * 50ms = 300ms` in ideal conditions, but on slow CI runners (Humble Pixi) the thread scheduling overhead and mock setup time push it past 500ms.

### Suggested fix

Replace the fixed `sleep_for(500ms)` with a polling loop that checks `plugin_->store().get("backoff_test")` with a reasonable timeout (e.g. 2s). This avoids adding more `thread::sleep` while making the test robust to CI runner speed. Pattern already used in integration tests via `poll_endpoint_until`.

### Environment
- ros2_medkit version: main (post-PR #289 merge)
- ROS 2 distro: Humble (Pixi environment)
- OS: Ubuntu 22.04 (GitHub Actions runner)

### Additional information

The Jazzy CI and regular Humble CI passed - only Pixi (humble) failed, suggesting the Pixi environment has slightly higher overhead.

### LINKED ISSUE #315: [BUG] Flaky test_operation_handlers SIGABRT on Pixi Humble CI
### Steps to reproduce
1. Run Pixi Humble CI (test_operation_handlers, test 42)
2. GetExecutionContainsStatusFields test occasionally crashes during teardown

### Expected behavior
Test passes cleanly.

### Actual behavior
`terminate called without an active exception` (SIGABRT, return code -6) after action goal subscription in GetExecutionContainsStatusFields. Race condition in action subscription cleanup during fixture teardown.

### Environment
- Pixi Humble only (Jazzy and Rolling pass)
- CI run: https://github.com/selfpatch/ros2_medkit/actions/runs/23639795178/job/68857384358

### PR DESCRIPTION
**Pull request by bburda**
## Summary

Systematic fix for all known flaky tests and shutdown crashes. Removes SIGSEGV from allowed exit codes to stop masking real crashes, then fixes every crash that surfaces.

**Shutdown crash fixes (production code):**
- Add destructors to OperationManager, LogManager, TriggerFaultSubscriber, SseFaultHandler - clear ROS 2 subscriptions with `this`-capturing callbacks before destruction
- Clear action_clients_ and generic_clients_ in OperationManager destructor - Humble compat GenericServiceClient shim crashes on unfulfilled promises
- Join capture threads in FaultManagerNode destructor - detached snapshot/rosbag threads accessed destroyed node pointer (SIGSEGV)

**Test infrastructure fixes:**
- Fix test_operation_handlers teardown order: destroy executor before nodes (prevents SIGABRT on all distros)
- Remove SIGSEGV (-11) from ALLOWED_EXIT_CODES - crashes are no longer masked
- Replace fixed 500ms sleep with polling in ParamBeacon BackoffOnTimeout test
- Reduce DISCOVERY_INTERVAL from 1.0s to 0.5s for integration tests

**Discovery bug fix:**
- Filter synthetic areas for root-namespace node names - prevents false areas from topic prefixes (e.g., /fault_manager/events no longer creates a "fault_manager" area)
- Behavioral change: root-namespace node topic prefixes no longer appear as synthetic areas in GET /areas

**Test isolation (new):**
- Add ROS2MedkitTestDomain.cmake macro for centralized ROS_DOMAIN_ID allocation
- Each package gets a non-overlapping domain range with overflow protection
- Assign domain IDs to 9 tests that previously ran on default domain 0
- Migrate all packages from hardcoded IDs to the macro

---

## Issue

- closes #315
- closes #297
- closes #296

---

## Type

- [x] Bug fix
- [x] New feature or tests
- [ ] Breaking change
- [ ] Documentation only

---

## Testing

- 2120 unit tests pass locally (0 failures)
- All CI jobs pass: Jazzy, Humble, Rolling, Pixi Humble, Pixi Jazzy, coverage, lint
- Shutdown crashes verified fixed across all distros after removing SIGSEGV from allowed codes

---

## Checklist

- [x] Breaking changes are clearly described (and announced in docs / changelog if needed)
- [x] Tests were added or updated if needed
- [x] Docs were updated if behavior or public API changed

### CODE REVIEW

File: src/ros2_medkit_gateway/test/test_helpers.hpp [hunk 1]
```diff
@@ -0,0 +1,39 @@
...
+    if (pred()) {
+      return true;
+    }
+    std::this_thread::sleep_for(interval);
+  }
+  return false;
+}
+
+}  // namespace testing
+}  // namespace ros2_medkit_gateway
```
[the remark this answers is not in the document]
Comment (bburda) [reply src/ros2_medkit_gateway/test/test_helpers.hpp]: Removed in 9484fe8. ParamBeacon is a separate package and can't include gateway test headers.

File: src/ros2_medkit_fault_manager/src/fault_manager_node.cpp [hunk 2]
```diff
@@ -372,14 +392,32 @@ void FaultManagerNode::handle_report_fault(
...
       auto rosbag_cap = rosbag_capture_;
       auto logger = get_logger();
-      std::thread([snapshot_cap, rosbag_cap, fault_code, logger]() {
+
+      {
+        std::lock_guard<std::mutex> ct_lock(capture_threads_mutex_);
+        // Join and remove finished threads before adding new one
+        for (auto it = capture_threads_.begin(); it != capture_threads_.end();) {
+          // Threads that are no longer joinable have been joined or moved
+          if (!it->joinable()) {
```
Comment (mfaferek93) [inline src/ros2_medkit_fault_manager/src/fault_manager_node.cpp]: **Minor**: This prune loop is dead code. Per C++ standard, `std::thread::joinable()` returns `true` for finished-but-not-joined threads. A thread only becomes non-joinable when explicitly `join()`'d, `detach()`'d, moved-from, or default-constructed. Since none of these apply to threads in `capture_threads_`, `!it->joinable()` is always `false` and the loop erases nothing.

The vector grows by one entry per fault report and is only cleaned up in the destructor. For typical fault counts this is negligible, but the code gives a false impression of incremental cleanup.

Simplest fix: remove the prune loop entirely (destructor handles it). Or add a per-thread `std::atomic<bool> done` flag and join+erase when set.

File: src/ros2_medkit_integration_tests/CMakeLists.txt [hunk 3]
```diff
@@ -107,10 +109,10 @@ if(BUILD_TESTING)
     )
     set_tests_properties(${test_name} PROPERTIES
       LABELS "integration;feature"
-      ENVIRONMENT "GATEWAY_TEST_PORT=${_INTEG_PORT};ROS_DOMAIN_ID=${_INTEG_DOMAIN_ID}"
+      ENVIRONMENT "GATEWAY_TEST_PORT=${_INTEG_PORT};ROS_DOMAIN_ID=${_MEDKIT_DOMAIN_COUNTER}"
     )
+    math(EXPR _MEDKIT_DOMAIN_COUNTER "${_MEDKIT_DOMAIN_COUNTER} + 1")
```
Comment (mfaferek93) [inline src/ros2_medkit_integration_tests/CMakeLists.txt:114]: **Minor**: This manual `math(EXPR)` increment bypasses the bounds check in `medkit_set_test_domain()`. Currently 58 test files use 64% of the 90-slot range (140-229). If >90 tests are added, the counter silently exceeds 229 without FATAL_ERROR.

Add a post-loop guard:
```cmake
if(_MEDKIT_DOMAIN_COUNTER GREATER _MEDKIT_DOMAIN_END)
  message(FATAL_ERROR "Integration test domain range exhausted")
endif()
```

File: src/ros2_medkit_fault_manager/src/fault_manager_node.cpp (hunk 2 above)
Comment (bburda) [reply src/ros2_medkit_fault_manager/src/fault_manager_node.cpp]: Fixed in 872e116 - removed the dead prune loop. Destructor joins all threads.

File: src/ros2_medkit_integration_tests/CMakeLists.txt (hunk 3 above)
Comment (bburda) [reply src/ros2_medkit_integration_tests/CMakeLists.txt:114]: Fixed in 872e116 - added post-loop bounds check.
