### PR TITLE
fix(gateway): use timed_mutex with 3s timeout to prevent permanent thread pool exhaustion

### LINKED ISSUE #332: Gateway becomes permanently unresponsive when configurations endpoint blocks spin_mutex
# Bug report

### Steps to reproduce
1. Start gateway with SSE enabled (default) on a system with nodes that accept parameter service but respond slowly (e.g., autostart_node on ROSMASTER M3 Pro)
2. Connect web UI - it opens SSE stream + loads entity tree + fetches configurations for each entity
3. One configurations request hits a slow node, acquires spin_mutex_, and blocks inside spin_node_until_future_complete
4. All subsequent configurations requests queue on spin_mutex_
5. httplib thread pool (8 workers) fills up with blocked threads
6. Gateway stops responding to ALL HTTP requests permanently

### Expected behavior

Gateway should remain responsive even when some nodes are slow to respond to parameter service calls. Other endpoints (health, data, faults, entity tree) should not be affected.

### Actual behavior

Gateway process alive (discovery continues) but httplib completely unresponsive. gdb shows 7+ threads blocked on the same futex (spin_mutex_). Only kill -9 recovers.

Confirmed via gdb thread dump:
```
Thread 30: futex_wait -> lll_lock_wait -> pthread_mutex_lock (spin_mutex_)
Thread 29: futex_wait -> lll_lock_wait -> pthread_mutex_lock (spin_mutex_)
Thread 28: futex_wait -> lll_lock_wait -> pthread_mutex_lock (spin_mutex_)
...
Thread 23: futex_abstimed_wait -> pthread_cond_wait (holding spin_mutex_, waiting on spin_node_until_future_complete)
```

### Root cause

spin_mutex_ in ConfigurationManager serializes ALL parameter service IPC calls. If one SyncParametersClient::list_parameters() call hangs (node accepts service but never responds), spin_mutex_ is held indefinitely. All other configuration requests block waiting for the mutex, exhausting the httplib thread pool.

### Environment
- ros2_medkit version: main (post #318 merge)
- ROS 2 distro: Humble
- OS: Ubuntu 22.04 on Jetson Orin Nano (aarch64)
- Robot: Yahboom ROSMASTER M3 Pro with micro-ROS nodes

### PR DESCRIPTION
**Pull request by mfaferek93**
## Summary

spin_mutex_ in ConfigurationManager blocked indefinitely when a node accepted parameter service but never responded. One hung thread held the mutex forever, all subsequent configurations requests queued on it, exhausting httplib's 8-thread pool. Gateway became permanently unresponsive.

Replace std::mutex with std::timed_mutex. All public methods use try_lock_for(3s) - if mutex unavailable, return TIMEOUT error instead of blocking forever.

## Test plan

- [x] 22/22 unit tests pass
- [x] 58/58 integration tests pass (100%)
- [x] Tested on Jetson Orin Nano with SSE enabled + web UI: stable after fix
- [x] Confirmed via gdb: before fix, 7 threads blocked on spin_mutex_; after fix, threads return with TIMEOUT

Fixes #332

### CODE REVIEW

File: src/ros2_medkit_gateway/src/configuration_manager.cpp [hunk 1]
```diff
@@ -62,7 +62,7 @@ void ConfigurationManager::shutdown() {
     return;  // Already shut down
   }
   // Acquire spin_mutex_ first to wait for any in-flight IPC to complete
-  std::lock_guard<std::mutex> spin_lock(spin_mutex_);
+  std::lock_guard<std::timed_mutex> spin_lock(spin_mutex_);
   std::lock_guard<std::mutex> lock(clients_mutex_);
```
[the remark this answers is not in the document]
Comment (mfaferek93) [reply src/ros2_medkit_gateway/src/configuration_manager.cpp:70]: Fixed. shutdown() now uses try_lock_for(kShutdownTimeout=10s) with best-effort cleanup on timeout + warning log.

File: src/ros2_medkit_gateway/src/configuration_manager.cpp [hunk 2]
```diff
@@ -226,7 +226,13 @@ ParameterResult ConfigurationManager::list_parameters(const std::string & node_n
...
     std::vector<rclcpp::Parameter> parameters;
     {
-      std::lock_guard<std::mutex> spin_lock(spin_mutex_);
+      if (!spin_mutex_.try_lock_for(std::chrono::seconds(3))) {
+        result.success = false;
+        result.error_message = "Parameter service busy (spin lock timeout)";
+        result.error_code = ParameterErrorCode::TIMEOUT;
+        return result;
+      }
+      std::lock_guard<std::timed_mutex> spin_lock(spin_mutex_, std::adopt_lock);
```
[the remark this answers is not in the document]
Comment (mfaferek93) [reply src/ros2_medkit_gateway/src/configuration_manager.cpp]: Fixed. Extracted try_acquire_spin_lock() helper with kSpinLockTimeout constant. All 5 call sites use the helper.

File: src/ros2_medkit_gateway/src/configuration_manager.cpp [hunk 3]
```diff
@@ -61,8 +61,13 @@ void ConfigurationManager::shutdown() {
...
     return;  // Already shut down
   }
-  // Acquire spin_mutex_ first to wait for any in-flight IPC to complete
-  std::lock_guard<std::mutex> spin_lock(spin_mutex_);
+  // Wait for in-flight IPC with generous timeout, proceed with cleanup regardless
+  if (!spin_mutex_.try_lock_for(kShutdownTimeout)) {
+    RCLCPP_WARN(node_->get_logger(),
+                "ConfigurationManager shutdown: spin_mutex_ not released within timeout, proceeding with cleanup");
+  } else {
+    spin_mutex_.unlock();
```
Comment (bburda) [inline src/ros2_medkit_gateway/src/configuration_manager.cpp]: Regression vs main: current main holds `spin_mutex_` through entire cleanup via `lock_guard`. Here it's acquire + immediate unlock before `param_clients_.clear()` and `param_node_.reset()`.

Race: thread A passed `shutdown_.load()` check in `set_parameter` but hasn't acquired `spin_mutex_` yet. Thread B (shutdown) acquires + releases `spin_mutex_`, then clears `param_clients_` and resets `param_node_`. Thread A acquires `spin_mutex_`, calls `get_param_client()` which constructs `SyncParametersClient(param_node_, ...)` on nullptr.

Fix - hold `unique_lock` through cleanup:
```cpp
std::unique_lock<std::timed_mutex> spin_lock(spin_mutex_, std::defer_lock);
if (!spin_lock.try_lock_for(kShutdownTimeout)) {
    RCLCPP_WARN(...);
}
std::lock_guard<std::mutex> clients_lock(clients_mutex_);
param_clients_.clear();
param_node_.reset();
```

File: src/ros2_medkit_gateway/src/configuration_manager.cpp [hunk 4]
```diff
@@ -72,6 +77,18 @@ ParameterResult ConfigurationManager::shut_down_result() {
   return {false, {}, "ConfigurationManager is shut down", ParameterErrorCode::SHUT_DOWN};
 }
 
+bool ConfigurationManager::try_acquire_spin_lock(ParameterResult & result) {
+  auto timeout = std::chrono::duration_cast<std::chrono::milliseconds>(
+      std::chrono::duration<double>(service_timeout_sec_ + kSpinLockMarginSec));
+  if (!spin_mutex_.try_lock_for(timeout)) {
+    result.success = false;
+    result.error_message = "Parameter service busy (spin lock timeout)";
```
Comment (bburda) [inline src/ros2_medkit_gateway/src/configuration_manager.cpp]: Two things:

1. **Error message** - "spin lock" is a C++ concurrency term, meaningless to REST API / MCP / web UI consumers. Other timeouts in the codebase are user-facing, e.g. `"Service call timed out (2s): /path"`. Suggest: `"Parameter service temporarily unavailable - timed out after Xs"` with the actual timeout value.

2. **Missing RCLCPP_WARN** - every other failure path in this class (`wait_for_service`, shutdown timeout) logs WARN. This path is completely silent. When a node hangs and requests start timing out, operators see nothing in logs. Add:
```cpp
RCLCPP_WARN(node_->get_logger(),
    "Parameter service spin lock timeout (%.1fs) - another operation may be blocking",
    service_timeout_sec_ + kSpinLockMarginSec);
```

File: src/ros2_medkit_gateway/src/configuration_manager.cpp [hunk 5]
```diff
@@ -72,6 +77,18 @@ ParameterResult ConfigurationManager::shut_down_result() {
   return {false, {}, "ConfigurationManager is shut down", ParameterErrorCode::SHUT_DOWN};
 }
 
+bool ConfigurationManager::try_acquire_spin_lock(ParameterResult & result) {
```
Comment (bburda) [inline src/ros2_medkit_gateway/src/configuration_manager.cpp]: Suggestion: on success this leaves `spin_mutex_` locked and relies on caller to construct `lock_guard(spin_mutex_, adopt_lock)`. If anything between the check and the `lock_guard` throws, the mutex is locked forever.

Alternative: return `std::optional<std::unique_lock<std::timed_mutex>>` - empty on timeout, populated on success. Ownership enforced by the type system, exception-safe by construction.

Also missing: tests for the new TIMEOUT path. None of the 22 existing unit tests exercise this code. Need at minimum a test that holds `spin_mutex_` from a background thread and asserts the public method returns `ParameterErrorCode::TIMEOUT` within bounded time.

File: src/ros2_medkit_gateway/src/configuration_manager.cpp (hunk 3 above)
Comment (mfaferek93) [reply src/ros2_medkit_gateway/src/configuration_manager.cpp]: Fixed. shutdown() now holds unique_lock through entire cleanup - no acquire+release race.

File: src/ros2_medkit_gateway/src/configuration_manager.cpp (hunk 4 above)
Comment (mfaferek93) [reply src/ros2_medkit_gateway/src/configuration_manager.cpp]: Fixed both. Error message now user-facing: "Parameter service temporarily unavailable - timed out after Xs". Added RCLCPP_WARN on timeout.

File: src/ros2_medkit_gateway/src/configuration_manager.cpp (hunk 5 above)
Comment (mfaferek93) [reply src/ros2_medkit_gateway/src/configuration_manager.cpp]: Fixed. try_acquire_spin_lock now returns std::optional<std::unique_lock<std::timed_mutex>> - ownership enforced by type system, exception-safe. Added test_spin_lock_timeout_returns_error (23/23 pass).
