### PR TITLE
fix: suppress root-namespace heuristic entities and orphan apps

### LINKED ISSUE #1: Add devcontainer for ROS 2 development
Add a VS Code Dev Container so development happens in a reproducible ROS 2 environment.

### LINKED ISSUE #307: [BUG] Hybrid discovery merge pipeline does not suppress runtime entities linked to manifest entities
# Bug report

### Steps to reproduce

1. Configure gateway in hybrid mode with a manifest that defines entities with hyphenated IDs (e.g., `lidar-sim`, `fault-manager`)
2. Ensure `create_synthetic_components: false` in config (though the bug occurs regardless of this setting)
3. Start the gateway with ROS 2 nodes whose names match manifest `ros_binding` entries
4. Query entity collection endpoints (`GET /areas`, `/components`, `/apps`)

Reproducible with any selfpatch_demos demo (sensor_diagnostics, moveit_pick_place, turtlebot3_integration).

### Expected behavior

After runtime linking matches runtime nodes to manifest entities via `ros_binding`, the merge pipeline should emit only the manifest-defined entities. Linked runtime entities should be suppressed/merged into their manifest counterparts.

For sensor_diagnostics demo:
- Areas: 4 (sensors, processing, diagnostics, bridge)
- Components: 8 (lidar-unit, imu-unit, gps-unit, camera-unit, compute-unit, gateway, fault-manager, diagnostic-bridge-unit)
- Apps: 8 (lidar-sim, imu-sim, gps-sim, camera-sim, anomaly-detector, medkit-gateway, medkit-fault-manager, diagnostic-bridge)

### Actual behavior

Both manifest entities AND linked runtime entities appear in API responses, creating duplicates:

**Areas: 6 instead of 4**
```
sensors, processing, diagnostics, bridge, fault_manager, root
```
Extra: `fault_manager` (synthetic area from runtime), `root` (synthetic area)

**Components: 17 instead of 8**
```
lidar-unit, imu-unit, gps-unit, camera-unit, compute-unit, gateway, fault-manager, diagnostic-bridge-unit,
lidar_sim, camera_sim, imu_sim, gps_sim, anomaly_detector, diagnostic_bridge, ros2_medkit_gateway, _param_client_node, fault_manager
```
The bottom 9 are runtime-created synthetic entities with underscored IDs that should have been merged.

**Apps: 17 instead of 8**
Same pattern - every manifest app has a corresponding unmerged runtime duplicate.

Gateway logs show linking succeeds but duplicates still appear:
```
Runtime linking: 8 linked, 9 unlinked, 1 orphan nodes
MergePipeline: 43 entities from 4 layers, 4 enriched, 0 conflicts
```

The merge pipeline likely compares entity IDs directly (underscored != hyphenated) instead of using the `ros_binding` linkage to identify duplicates.

### Environment
- ros2_medkit version: main (v0.4.0)
- ROS 2 distro: Jazzy
- OS: Ubuntu 24.04 (Docker)

### Additional information

- `create_synthetic_components: false` does not prevent this - it only changes the grouping strategy, not whether runtime entities are created
- The graph_provider plugin is NOT the source of duplicates - it only enriches existing entities, does not create new ones
- Discovered while adding entity count assertions to selfpatch_demos smoke tests (selfpatch/selfpatch_demos#53)

### PR DESCRIPTION
**Pull request by bburda**
# Pull Request

## Summary

Fix remaining entity suppression gaps in hybrid mode merge pipeline. After PR #311, gateway no longer crashes but still emits duplicate entities from root namespace and orphan nodes.

Three issues fixed:
1. **Root-namespace linked nodes** (e.g., `/fault_manager`) - `linked_namespaces` now includes `"/"` for root-namespace FQNs (previously skipped due to `last_slash == 0` guard)
2. **Orphan heuristic apps** (e.g., `_param_client_node`) - in hybrid mode with manifest, heuristic apps not present in manifest are suppressed
3. **Root heuristic areas** (e.g., `root` area) - now covered by fix #1

Before: sensor demo had 6 areas (expected 4), 10 components (expected 8), 9 apps (expected 8)
After: exact manifest counts

## Issue

- closes #307

## Type

- [x] Bug fix
- [ ] New feature or tests
- [ ] Breaking change
- [ ] Documentation only

## Testing

- 3 new unit tests: `SuppressRootNamespaceHeuristicComponents`, `SuppressRootNamespaceHeuristicAreas`, `SuppressOrphanHeuristicApps`
- Full merge pipeline suite: 72/72 pass
- Pre-commit hooks pass
- selfpatch_demos PR #53 entity count assertions should pass after merge

## Checklist

- [x] Breaking changes are clearly described (and announced in docs / changelog if needed)
- [x] Tests were added or updated if needed
- [ ] Docs were updated if behavior or public API changed

### CODE REVIEW

File: src/ros2_medkit_gateway/include/ros2_medkit_gateway/discovery/merge_types.hpp [hunk 1]
```diff
@@ -151,5 +151,15 @@ struct GapFillConfig {
...
 };
 
+/**
+ * @brief Check if an entity source is from runtime discovery (eligible for suppression)
+ *
+ * Runtime sources (heuristic, topic, synthetic) are created by the runtime discovery
+ * layer and may duplicate manifest entities. Manifest and plugin sources are preserved.
+ */
+inline bool is_runtime_source(const std::string & source) {
+  return source == "heuristic" || source == "topic" || source == "synthetic";
```
Comment (mfaferek93) [inline src/ros2_medkit_gateway/include/ros2_medkit_gateway/discovery/merge_types.hpp]: **Minor**: Misses `"node"` - the default `Component::source` value in `component.hpp:40`. If any future code path creates an entity without explicitly setting `.source`, it would bypass suppression. Current runtime discovery paths all set source explicitly, but this is a latent gap.

Consider adding `"node"` here, or changing the default Component::source to `"unknown"` and treating it as non-suppressible.

File: src/ros2_medkit_gateway/src/discovery/merge_pipeline.cpp [hunk 2]
```diff
@@ -513,10 +527,35 @@ MergeResult MergePipeline::execute() {
...
+    // Remove heuristic apps that were merged into manifest apps (same ID after merge).
+    // These are runtime duplicates of linked manifest entities. Gap-fill apps (new
+    // heuristic apps in any namespace) survive - they fill manifest gaps intentionally.
+    std::set<std::string> manifest_app_ids;
+    for (const auto & app : result.apps) {
+      if (app.source == "manifest") {
+        manifest_app_ids.insert(app.id);
+      }
+    }
+    // node_to_app values are always manifest app IDs (RuntimeLinker maps FQN -> manifest ID),
```
Comment (mfaferek93) [inline src/ros2_medkit_gateway/src/discovery/merge_pipeline.cpp]: **Minor**: This app ID suppression appears to be a defensive no-op in practice. Real suppression happens at two earlier stages: (1) `merge_entities` combines same-ID manifest+runtime into one entity with manifest source winning, (2) linker `remove_if` suppresses different-ID runtime apps by FQN match.

The test at line 374 confirms both removed apps are "FQN-deduped" by the linker, not by this code. Line 539-540 acknowledges: "linked_app_ids == manifest_app_ids in practice."

Not blocking - defensive layers are fine. But the comment could be more explicit that this is future-proofing, not handling a current scenario.

File: src/ros2_medkit_gateway/src/discovery/merge_pipeline.cpp [hunk 3]
```diff
@@ -513,6 +519,28 @@ MergeResult MergePipeline::execute() {
...
+    if (has_manifest) {
+      auto app_it = std::remove_if(result.apps.begin(), result.apps.end(), [&](const App & app) {
+        if (app.source != "heuristic" && app.source != "topic" && app.source != "synthetic") {
+          return false;
+        }
+        // Suppress if this heuristic app was not linked to a manifest app
+        return manifest_app_ids.find(app.id) == manifest_app_ids.end();
+      });
+      result.apps.erase(app_it, result.apps.end());
+    }
```
[the remark this answers is not in the document]
Comment (bburda) [reply src/ros2_medkit_gateway/src/discovery/merge_pipeline.cpp]: The current code does NOT drop all runtime apps - it only suppresses apps whose ID matches `linked_app_ids`. Orphan apps like `_param_client_node` survive because their ID is not in the set. The test at line 1863 asserts this: orphans survive.

The `unmanifested_nodes` policy point is valid for a future enhancement but out of scope for this fix - the current behavior (orphans survive under `warn` default) is correct.

File: src/ros2_medkit_gateway/test/test_merge_pipeline.cpp [hunk 4]
```diff
@@ -1669,3 +1669,162 @@ TEST_F(MergePipelineTest, AddLayerAfterExecuteDoesNotCrash) {
...
+  pipeline_.add_layer(std::make_unique<TestLayer>(
+      "manifest", manifest_out,
+      std::unordered_map<FieldGroup, MergePolicy>{{FieldGroup::IDENTITY, MergePolicy::AUTHORITATIVE}}));
+  pipeline_.add_layer(std::make_unique<TestLayer>(
+      "runtime", runtime_out,
+      std::unordered_map<FieldGroup, MergePolicy>{{FieldGroup::STATUS, MergePolicy::AUTHORITATIVE}}));
+
+  ManifestConfig manifest_config;
+  pipeline_.set_linker(std::make_unique<RuntimeLinker>(nullptr), manifest_config);
+
```
[the remark this answers is not in the document]
Comment (bburda) [reply src/ros2_medkit_gateway/test/test_merge_pipeline.cpp:1852]: The test asserts the opposite of what this comment says - `_param_client_node` SURVIVES (line 1863), it is NOT suppressed. The default `warn` policy is correctly reflected: orphan heuristic apps persist.

File: src/ros2_medkit_gateway/include/ros2_medkit_gateway/discovery/merge_types.hpp (hunk 1 above)
Comment (bburda) [reply src/ros2_medkit_gateway/include/ros2_medkit_gateway/discovery/merge_types.hpp]: Good catch - added `"node"` to `is_runtime_source()`. This is the default `Component::source` in component.hpp:40 and should be suppressible.

File: src/ros2_medkit_gateway/src/discovery/merge_pipeline.cpp (hunk 2 above)
Comment (bburda) [reply src/ros2_medkit_gateway/src/discovery/merge_pipeline.cpp]: Updated the comment to explicitly state this is future-proofing and that real suppression happens at two earlier stages (merge_entities same-ID dedup + linker FQN-based dedup).
