### PR TITLE
fix(gateway): #153 serialize parameter operations to prevent executor…

### LINKED ISSUE #153: [BUG] ConfigurationManager fails with concurrent HTTP requests due to SyncParametersClient executor conflict
# Bug report

Please use this template to report bugs.

### Steps to reproduce
1. Start ros2_medkit_gateway with multiple ROS 2 nodes (e.g., sensor_diagnostics demo)                                                                               
2. Send concurrent HTTP requests for configurations of different nodes (e.g., UI expanding multiple entities)                                                        
3. Observe error in gateway logs  

### Expected behavior

All concurrent configuration requests complete successfully. 

### Actual behavior

[ERROR] Exception in list_parameters for node '/bt_navigator': Node '/_param_client_node' has already been added to an executor.                        
                                                                                      
SyncParametersClient internally spins param_node_ via spin_node_until_future_complete(). Concurrent requests spin the same node simultaneously, causing the executor conflict. 

### Environment
- ros2_medkit version: main (9310af2)                                               
- ROS 2 distro: Jazzy                                                               
- OS: Ubuntu 24.04  

### Additional information
Root cause: spin_node_until_future_complete() is not thread-safe                    
(https://github.com/ros2/rclcpp/issues/206).                                        
                                                                                      
Proposed fix: Add std::recursive_mutex to serialize parameter operations in         
ConfigurationManager. Recursive mutex needed because list_parameters() calls cache_default_values() internally.

### PR DESCRIPTION
**Pull request by mfaferek93**
# Pull Request

## Summary

serialize parameter operations to prevent executor conflicts
    
SyncParametersClient internally spins param_node_ via spin_node_until_future_complete(),
which is not thread-safe. Concurrent HTTP requests would cause:
Node /_param_client_node has already been added to an executor
    
Add recursive_mutex to serialize all parameter operations (list, get, set, reset).
Using recursive_mutex because list_parameters() calls cache_default_values() internally.

---

## Issue

Link the related issue (required):

- closes #153 

---

## Type

- [x] Bug fix
- [ ] New feature or tests
- [ ] Breaking change
- [ ] Documentation only

---

## Testing

How was this tested / how should reviewers verify it?

---

## Checklist

- [ ] Breaking changes are clearly described (and announced in docs / changelog if needed)
- [x] Tests were added or updated if needed
- [ ] Docs were updated if behavior or public API changed

### CODE REVIEW

File: src/ros2_medkit_gateway/test/test_configuration_manager.cpp [hunk 1]
```diff
@@ -345,6 +345,95 @@ TEST_F(TestConfigurationManager, test_concurrent_parameter_access) {
...
+  std::atomic<int> exception_count{0};
+  std::atomic<bool> start_flag{false};
+
+  // Spawn threads that will all start simultaneously
+  for (int i = 0; i < kNumThreads; ++i) {
+    threads.emplace_back([this, i, &success_count, &exception_count, &start_flag]() {
+      // Wait for all threads to be ready
+      while (!start_flag.load()) {
+        std::this_thread::yield();
+      }
```
[the remark this answers is not in the document]
Comment (mfaferek93) [reply src/ros2_medkit_gateway/test/test_configuration_manager.cpp:376]: This test takes only 30ms and threads are waiting only micro seconds, so I will keep it as it is right now

File: src/ros2_medkit_gateway/test/test_configuration_manager.cpp [hunk 2]
```diff
@@ -345,6 +345,95 @@ TEST_F(TestConfigurationManager, test_concurrent_parameter_access) {
   EXPECT_GE(success_count.load(), 1);
 }
 
+TEST_F(TestConfigurationManager, test_concurrent_parameter_operations_no_executor_error) {
```
Comment (bburda) [inline src/ros2_medkit_gateway/test/test_configuration_manager.cpp:348]: @mfaferek93 Could you also add a test that calls `reset_all_parameters`?

Comment (mfaferek93) [reply src/ros2_medkit_gateway/test/test_configuration_manager.cpp:348]: sure, added
