### PR TITLE
[#139] fix(gateway): aggregate configurations for aggregate SOVD entities

### LINKED ISSUE #149: [BUG] Configuration endpoints return 503 for aggregate entities (Areas, Components, Functions)
# Bug report

### Steps to reproduce
1. Start the gateway with demo nodes (`ros2 launch ros2_medkit_gateway gateway.launch.py`)
2. Call `GET /api/v1/areas/powertrain/configurations`
3. Or call `GET /api/v1/components/engine/configurations`
4. Or call `GET /api/v1/functions/{any_function}/configurations`

### Expected behavior

Configuration endpoints should return aggregated parameters from all child Apps, similar to how `/data` and `/operations` endpoints work for aggregate entities.

### Actual behavior

Returns `503 Service Unavailable` with error:
```json
{
  "error_code": "x-medkit-ros2-node-unavailable",
  "message": "Failed to list parameters",
  "parameters": {
    "node_name": "/powertrain"
  }
}

### PR DESCRIPTION
**Pull request by bburda**
# Pull Request

## Summary

Add configuration aggregation for Areas, Components, and Functions by collecting parameters from all child App nodes. Implements pattern used by data/operations endpoints. Parameter IDs use "app_id:param_name" format for disambiguation. Updates endpoint documentation and adds smoke test.

---

## Issue

Link the related issue (required):

- closes #149 

---

## Type

- [x] Bug fix
- [ ] New feature or tests
- [ ] Breaking change
- [ ] Documentation only

---

## Testing

How was this tested / how should reviewers verify it?
colcon test

---

## Checklist

- [x] Breaking changes are clearly described (and announced in docs / changelog if needed)
- [x] Tests were added or updated if needed
- [x] Docs were updated if behavior or public API changed

### CODE REVIEW

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp [hunk 1]
```diff
@@ -130,67 +181,125 @@ void ConfigHandlers::handle_get_configuration(const httplib::Request & req, http
...
+        response["x-medkit"] = ext.build();
+
+        HandlerContext::send_json(res, response);
+        return;
       }
     }
+
+    // Parameter not found in any node
+    HandlerContext::send_error(res, StatusCode::NotFound_404, ERR_RESOURCE_NOT_FOUND, "Parameter not found",
+                               {{"entity_id", entity_id}, {"id", param_id}});
```
[the remark this answers is not in the document]
Comment (bburda) [reply src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp]: Fixed.

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp [hunk 2]
```diff
@@ -24,6 +24,109 @@ using httplib::StatusCode;
...
+    result.status_code = StatusCode::NotFound_404;
+    result.error_code = ERR_RESOURCE_NOT_FOUND;
+  } else if (error_message.find("read-only") != std::string::npos ||
+             error_message.find("read only") != std::string::npos ||
+             error_message.find("is read_only") != std::string::npos) {
+    result.status_code = StatusCode::Forbidden_403;
+    result.error_code = ERR_X_MEDKIT_ROS2_PARAMETER_READ_ONLY;
+  } else if (error_message.find("not available") != std::string::npos ||
+             error_message.find("service not available") != std::string::npos ||
+             error_message.find("timed out") != std::string::npos ||
```
Comment (mfaferek93) [inline src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp:176]: if ConfigurationManager changes its error messages, this could break silently.                                                                               
                                                                                                                     
Would it be worth adding error codes to `ConfigurationManager::Result` in a future PR? Then we wouldn't rely on string parsing.                                                                                                    
                                                                                                                     
  Not blocking for this PR.

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp [hunk 3]
```diff
@@ -49,45 +152,96 @@ void ConfigHandlers::handle_list_configurations(const httplib::Request & req, ht
...
-          config_meta["type"] = "parameter";  // ROS2 parameters are always parameter type (not bulk)
-          items.push_back(config_meta);
+    json items = json::array();
+    json all_parameters = json::array();
+    std::vector<std::string> queried_nodes;
+    bool any_success = false;
+    std::string first_error;
+
+    // Query each node and aggregate results
+    for (const auto & node_info : agg_configs.nodes) {
```
Comment (mfaferek93) [inline src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp:276]: For entities with many apps (e.g., a large Area), this loop queries each node sequentially. Have you considered parallelizing this similar to how DataAccessManager handles multiple topic samples?                                
                                                                                                                     
For now it's probably fine since parameter listing is typically fast, but worth keeping in mind if we see latency issues with large hierarchies.

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp [hunk 4]
```diff
@@ -49,45 +152,96 @@ void ConfigHandlers::handle_list_configurations(const httplib::Request & req, ht
...
+
+            // Also track full parameter info
+            json param_with_source = param;
+            param_with_source["x-medkit-source"] = node_info.app_id;
+            param_with_source["x-medkit-node"] = node_info.node_fqn;
+            all_parameters.push_back(param_with_source);
+          }
         }
+      } else if (first_error.empty()) {
+        first_error = result.error_message;
```
Comment (mfaferek93) [inline src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp:326]: Good that we track the first error! But we lose information about which node failed. Consider also tracking the node_fqn

File: src/ros2_medkit_gateway/src/models/thread_safe_entity_cache.cpp [hunk 5]
```diff
@@ -380,6 +380,177 @@ AggregatedOperations ThreadSafeEntityCache::get_function_operations(const std::s
...
+        info.node_fqn = *app.bound_fqn;
+        info.app_id = app.id;
+        info.entity_id = component_id;
+        result.nodes.push_back(info);
+        result.source_ids.push_back(app.id);
+      }
+    }
+    if (!apps_it->second.empty()) {
+      result.is_aggregated = true;
+    }
```
Comment (mfaferek93) [inline src/ros2_medkit_gateway/src/models/thread_safe_entity_cache.cpp]: Hmm, this sets is_aggregated=true even if there's only 1 app. Is that intentional?                                 
                                                                                                                     
A component with a single app would have is_aggregated=true, but an app directly would have is_aggregated=false.   
This might confuse clients expecting that is_aggregated means "data from multiple sources".

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp [hunk 6]
```diff
@@ -49,45 +152,96 @@ void ConfigHandlers::handle_list_configurations(const httplib::Request & req, ht
...
+        if (result.data.is_array()) {
+          for (const auto & param : result.data) {
+            json config_meta;
+            std::string param_name = param.value("name", "");
+
+            // Create unique ID for aggregated configs: node_fqn:param_name
+            std::string unique_id = param_name;
+            if (agg_configs.is_aggregated) {
+              unique_id = node_info.app_id + ":" + param_name;
+            }
```
[the remark this answers is not in the document]
Comment (bburda) [reply src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp]: Fixed.

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp (hunk 3 above)
Comment (bburda) [reply src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp:276]: Check now. Added multi-threaded approach.

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp (hunk 4 above)
Comment (bburda) [reply src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp:326]: Added Node information.

File: src/ros2_medkit_gateway/src/models/thread_safe_entity_cache.cpp (hunk 5 above)
Comment (bburda) [reply src/ros2_medkit_gateway/src/models/thread_safe_entity_cache.cpp]: Yh, changed it.

File: src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp (hunk 2 above)
Comment (bburda) [reply src/ros2_medkit_gateway/src/http/handlers/config_handlers.cpp:176]: Added enum for some errors. But I can't see any trivial solution to remove string find right now.
